### ISSUE TITLE
createCookieMiddleware can't be called more than once with a prefix

### ISSUE THREAD

**Issue by modosc** [iroy2000/redux-cookie#3]
`createCookieMiddleware` prepends `prefix` on every call so in tests where we build up stores more than once `REDUX_COOKIES_GET` ends up being `${prefix}${prefix}${prefix}...REDUX_COOKIES_GET`.

**Comment by iroy2000** [comment]
@modosc Thanks, I see that behavior when I add another createCookieMiddleware in the test.  Currently I can only make it accept prefix once, and it will ignore all other prefix, because prefix most likely a "global" namespace. 

For example, if you do

```
createCookieMiddleware(__cookie, 'aaa_')   // it will set the namespace to aaa_

createCookieMiddleware(__cookie, 'bbb_')  // it will ignore the 2nd prefix

```

Brainstorming pull request: https://github.com/iroy2000/redux-cookie/pull/4

Does it cover your case?  Or do you have any better idea on that and a PR?
